# Enhanced Combined System Maintenance Script with Prompts, Logging, Multi-Drive Support, and Expanded Analysis
# Version: 2.5.1
# Last Modified: August 16, 2025
# Author: Grok (Generated by xAI)
# Description: Changed Contig command from 'contig -v -s <drive>:\$MFT' to 'contig -v -accepteula <drive>:\$MFT' to remove recursive flag (-s) causing issues and add -accepteula for first-run license acceptance.
#              Added result-driven prompts for DISM commands (skip ScanHealth/RestoreHealth if CheckHealth finds no corruption,
#              skip StartComponentCleanup if AnalyzeComponentStore does not recommend it).
#              Added on-screen section summaries after each major section to guide user decisions.
#              Fixed PowerShell parsing errors in Temp File Cleanup section by using ${} for variables with colons.
#              Added temp file cleanup for C:\Windows\Temp, %TEMP%, and Windows Update cache.
#              Fixed SSD vs. HDD detection for accurate TRIM/defrag handling.
#              Includes hardware SMART checks, driver integrity, memory diagnostics, malware scans,
#              update checks, dirty volume queries, and broader Event Log analysis for corruption IDs.

# Must run as Administrator
#Requires -RunAsAdministrator

# Log file setup
$hostname = $env:COMPUTERNAME
$date = Get-Date -Format "yyyyMMdd"
$baseLogFile = "CombinedSystemMaintenanceLog_$hostname_$date"
$logFile = "$baseLogFile.txt"
$counter = 1
while (Test-Path $logFile) {
    $logFile = "${baseLogFile}_$counter.txt"
    $counter++
}
New-Item $logFile -ItemType File | Out-Null

# Function to log messages
function Write-Log {
    param($Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$timestamp - $Message" | Out-File -FilePath $logFile -Append
    Write-Host "$timestamp - $Message"
}

# Optional repair source for DISM /restorehealth
$repairSource = $null  # Example: "WIM:D:\sources\install.wim:1"

# Function to prompt user for Yes/No input
function Confirm-Action {
    param (
        [string]$Message,
        [string]$Default = "Y"
    )
    $validChoices = @("Y", "N")
    $choice = Read-Host "$Message (Y/N, default: $Default)"
    $choice = $choice.Trim().ToUpper()
    if (-not $choice) {
        $choice = $Default
    }
    if ($choice -notin $validChoices) {
        Write-Host "Invalid input. Using default: $Default" -ForegroundColor Yellow
        return $Default -eq "Y"
    }
    return $choice -eq "Y"
}

# Check for Sysinternals Suite
$sysinternalsPath = "C:\SysinternalsSuite"
if (-not (Test-Path $sysinternalsPath)) {
    Write-Host "`nSysinternals Suite not found at $sysinternalsPath" -ForegroundColor Yellow
    if (Confirm-Action -Message "Download and extract Sysinternals Suite to $sysinternalsPath and add to PATH?" -Default "N") {
        Write-Log "Downloading Sysinternals Suite..."
        try {
            $zipUrl = "https://download.sysinternals.com/files/SysinternalsSuite.zip"
            $tempZip = [System.IO.Path]::GetTempFileName() + ".zip"
            Invoke-WebRequest -Uri $zipUrl -OutFile $tempZip
            Write-Log "Extracting to $sysinternalsPath..."
            New-Item -Path $sysinternalsPath -ItemType Directory -Force | Out-Null
            Expand-Archive -Path $tempZip -DestinationPath $sysinternalsPath -Force
            Remove-Item -Path $tempZip
            Write-Log "Adding $sysinternalsPath to system PATH..."
            $currentPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
            if ($currentPath -notlike "*$sysinternalsPath*") {
                [Environment]::SetEnvironmentVariable("Path", "$currentPath;$sysinternalsPath", "Machine")
            }
            Write-Log "Successfully downloaded and extracted Sysinternals Suite"
        } catch {
            Write-Log "Error downloading Sysinternals Suite: $_"
        }
    } else {
        Write-Log "Skipped Sysinternals Suite download"
    }
}

# Check if Contig is available
$contigAvailable = Get-Command "contig" -ErrorAction SilentlyContinue

# Step 1: Check TRIM status
if (Confirm-Action -Message "Check and enable TRIM for SSD optimization?" -Default "Y") {
    Write-Log "Checking TRIM status..."
    $trimStatus = fsutil behavior query DisableDeleteNotify
    if ($trimStatus -match "DisableDeleteNotify = 0") {
        Write-Log "TRIM is enabled (good for SSD)"
    } else {
        Write-Log "TRIM is disabled. Enabling TRIM..."
        fsutil behavior set DisableDeleteNotify 0
        Write-Log "TRIM enabled"
    }
    Write-Host "`nTRIM Check Summary:" -ForegroundColor Green
    Write-Host "TRIM Status: $(if ($trimStatus -match 'DisableDeleteNotify = 0') { 'Enabled' } else { 'Disabled, now enabled' })"
} else {
    Write-Log "Skipped TRIM check"
}

# Step 2: Get all NTFS drives and their types
$physicalDisks = Get-PhysicalDisk | Select-Object DeviceId, MediaType, FriendlyName, UniqueId
$ntfsDrives = Get-Volume | Where-Object { $_.FileSystem -eq "NTFS" -and $_.DriveLetter } | ForEach-Object {
    $volume = $_
    $partition = Get-Partition | Where-Object { $_.DriveLetter -eq $volume.DriveLetter }
    $disk = if ($partition) { Get-Disk -Number ($partition.DiskNumber) } else { $null }
    $mediaType = if ($disk) {
        $physicalDisk = $physicalDisks | Where-Object { $_.UniqueId -eq $disk.UniqueId }
        if ($physicalDisk.MediaType) {
            $physicalDisk.MediaType
        } elseif ($physicalDisk.FriendlyName -match "SSD|NVMe") {
            "SSD"
        } else {
            "HDD"  # Default to HDD if unspecified and no SSD/NVMe in name
        }
    } else {
        "HDD"  # Default if no disk match
    }
    [PSCustomObject]@{
        DriveLetter = $volume.DriveLetter
        MediaType = $mediaType
        FriendlyName = if ($physicalDisk) { $physicalDisk.FriendlyName } else { "Unknown" }
    }
}
if (-not $ntfsDrives) {
    Write-Log "No NTFS drives found. Exiting."
    Write-Host "`nDrive Detection Summary:" -ForegroundColor Green
    Write-Host "No NTFS drives found. Exiting script."
    exit
}
$ssdDrives = $ntfsDrives | Where-Object { $_.MediaType -eq "SSD" } | Select-Object -ExpandProperty DriveLetter
$nonSsdDrives = $ntfsDrives | Where-Object { $_.MediaType -ne "SSD" } | Select-Object -ExpandProperty DriveLetter
Write-Log "Found NTFS drives: $($ntfsDrives.DriveLetter -join ', ')"
Write-Log "SSD drives: $($ssdDrives -join ', ')"
Write-Log "Non-SSD drives: $($nonSsdDrives -join ', ')"
foreach ($drive in $ntfsDrives) {
    Write-Log "Drive $($drive.DriveLetter): MediaType=$($drive.MediaType), FriendlyName=$($drive.FriendlyName)"
}
Write-Host "`nDrive Detection Summary:" -ForegroundColor Green
Write-Host "NTFS Drives: $($ntfsDrives.DriveLetter -join ', ')"
Write-Host "SSD Drives: $($ssdDrives -join ', ')"
Write-Host "Non-SSD Drives: $($nonSsdDrives -join ', ')"

# OS Maintenance Section
if (Confirm-Action -Message "Proceed with OS Maintenance (DISM and SFC)?" -Default "Y") {
    $osCommands = @(
        @{Command = "dism /online /cleanup-image /checkhealth"; Description = "CheckHealth - Check for component store corruption"},
        @{Command = "dism /online /cleanup-image /scanhealth"; Description = "ScanHealth - Perform a deeper scan for corruption"},
        @{Command = if ($repairSource) { "dism /online /cleanup-image /restorehealth /source:$repairSource" } else { "dism /online /cleanup-image /restorehealth" }; Description = "RestoreHealth - Repair the component store"},
        @{Command = "dism /online /cleanup-image /AnalyzeComponentStore"; Description = "AnalyzeComponentStore - Analyze component store size"},
        @{Command = "dism /online /cleanup-image /StartComponentCleanup"; Description = "StartComponentCleanup - Clean up superseded components"},
        @{Command = "sfc /scannow"; Description = "SFC Scan - Scan and repair system files"}
    )

    $skipScanHealth = $false
    $skipRestoreHealth = $false
    $skipComponentCleanup = $false
    $osErrors = 0
    $osRepairs = 0

    foreach ($cmd in $osCommands) {
        if ($cmd.Description -eq "ScanHealth - Perform a deeper scan for corruption" -and $skipScanHealth) {
            Write-Log "Skipped: $($cmd.Description) (no corruption found in CheckHealth)"
            continue
        }
        if ($cmd.Description -eq "RestoreHealth - Repair the component store" -and $skipRestoreHealth) {
            Write-Log "Skipped: $($cmd.Description) (no corruption found in CheckHealth)"
            continue
        }
        if ($cmd.Description -eq "StartComponentCleanup - Clean up superseded components" -and $skipComponentCleanup) {
            Write-Log "Skipped: $($cmd.Description) (AnalyzeComponentStore did not recommend cleanup)"
            continue
        }

        Write-Host "`nRunning: $($cmd.Description)" -ForegroundColor Cyan
        if (Confirm-Action -Message "Proceed with $($cmd.Description)?" -Default "Y") {
            Write-Log "Executing: $($cmd.Command)"
            try {
                if ($cmd.Command -eq "sfc /scannow") {
                    $tempFile = [System.IO.Path]::GetTempFileName()
                    Start-Process -FilePath "sfc" -ArgumentList "/scannow" -NoNewWindow -Wait -RedirectStandardOutput $tempFile -RedirectStandardError $tempFile
                    $output = Get-Content $tempFile
                    $output | Write-Host
                    $output | Out-File -FilePath $logFile -Append
                    Remove-Item $tempFile
                    if ($output -match "found.*and repaired") {
                        $osRepairs++
                    } elseif ($output -match "corrupt|cannot repair") {
                        $osErrors++
                    }
                } else {
                    $output = Invoke-Expression "$($cmd.Command) 2>&1" | Tee-Object -FilePath $logFile -Append
                    if ($cmd.Description -eq "CheckHealth - Check for component store corruption") {
                        if ($output -match "No component store corruption detected") {
                            Write-Host "`nCheckHealth Result: No corruption detected" -ForegroundColor Green
                            Write-Log "CheckHealth: No component store corruption detected"
                            if (Confirm-Action -Message "No corruption found. Skip ScanHealth and RestoreHealth?" -Default "N") {
                                $skipScanHealth = $true
                                $skipRestoreHealth = $true
                            }
                        } else {
                            Write-Host "`nCheckHealth Result: Corruption detected" -ForegroundColor Yellow
                            Write-Log "CheckHealth: Component store corruption detected"
                            $osErrors++
                        }
                    } elseif ($cmd.Description -eq "ScanHealth - Perform a deeper scan for corruption") {
                        if ($output -match "corrupt|error|failed") {
                            Write-Host "`nScanHealth Result: Corruption detected" -ForegroundColor Yellow
                            Write-Log "ScanHealth: Component store corruption detected"
                            $osErrors++
                        } else {
                            Write-Host "`nScanHealth Result: No corruption detected" -ForegroundColor Green
                            Write-Log "ScanHealth: No component store corruption detected"
                            if (Confirm-Action -Message "No corruption found in ScanHealth. Skip RestoreHealth?" -Default "N") {
                                $skipRestoreHealth = $true
                            }
                        }
                    } elseif ($cmd.Description -eq "RestoreHealth - Repair the component store") {
                        if ($output -match "successfully repaired|restored") {
                            Write-Host "`nRestoreHealth Result: Repairs completed" -ForegroundColor Green
                            Write-Log "RestoreHealth: Component store repairs completed"
                            $osRepairs++
                        } elseif ($output -match "corrupt|error|failed") {
                            Write-Host "`nRestoreHealth Result: Errors encountered" -ForegroundColor Yellow
                            Write-Log "RestoreHealth: Errors during repair"
                            $osErrors++
                        }
                    } elseif ($cmd.Description -eq "AnalyzeComponentStore - Analyze component store size") {
                        if ($output -match "reclaimable.*: *0" -or $output -notmatch "reclaim.*recommended") {
                            Write-Host "`nAnalyzeComponentStore Result: Cleanup not recommended" -ForegroundColor Green
                            Write-Log "AnalyzeComponentStore: Cleanup not recommended"
                            if (Confirm-Action -Message "Cleanup not recommended. Skip StartComponentCleanup?" -Default "N") {
                                $skipComponentCleanup = $true
                            }
                        } else {
                            Write-Host "`nAnalyzeComponentStore Result: Cleanup recommended" -ForegroundColor Yellow
                            Write-Log "AnalyzeComponentStore: Cleanup recommended"
                        }
                    } elseif ($cmd.Description -eq "StartComponentCleanup - Clean up superseded components") {
                        if ($output -match "successfully completed") {
                            Write-Host "`nStartComponentCleanup Result: Cleanup completed" -ForegroundColor Green
                            Write-Log "StartComponentCleanup: Cleanup completed"
                            $osRepairs++
                        } elseif ($output -match "error|failed") {
                            Write-Host "`nStartComponentCleanup Result: Errors encountered" -ForegroundColor Yellow
                            Write-Log "StartComponentCleanup: Errors during cleanup"
                            $osErrors++
                        }
                    }
                }
            } catch {
                Write-Log "Error executing $($cmd.Description): $_"
                Write-Host "`n$($cmd.Description) Result: Error - $_" -ForegroundColor Red
                $osErrors++
            }
            Write-Log "End of $($cmd.Description)"
        } else {
            Write-Log "Skipped: $($cmd.Description)"
        }
    }

    Write-Host "`nOS Maintenance Summary:" -ForegroundColor Green
    Write-Host "Errors Detected: $osErrors"
    Write-Host "Repairs Made: $osRepairs"
    if ($skipScanHealth -and $skipRestoreHealth) {
        Write-Host "Skipped ScanHealth and RestoreHealth due to no corruption in CheckHealth"
    } elseif ($skipRestoreHealth) {
        Write-Host "Skipped RestoreHealth due to no corruption in ScanHealth"
    }
    if ($skipComponentCleanup) {
        Write-Host "Skipped StartComponentCleanup as not recommended by AnalyzeComponentStore"
    }
    Write-Log "OS Maintenance Summary: Errors=$osErrors, Repairs=$osRepairs"
    if ($skipScanHealth -and $skipRestoreHealth) {
        Write-Log "Skipped ScanHealth and RestoreHealth due to no corruption in CheckHealth"
    }
    if ($skipRestoreHealth) {
        Write-Log "Skipped RestoreHealth due to no corruption in ScanHealth"
    }
    if ($skipComponentCleanup) {
        Write-Log "Skipped StartComponentCleanup as not recommended by AnalyzeComponentStore"
    }
} else {
    Write-Log "Skipped OS Maintenance section"
    Write-Host "`nOS Maintenance Summary: Skipped" -ForegroundColor Green
}

# Disk Maintenance Section
if (Confirm-Action -Message "Proceed with Disk Maintenance (CHKDSK, fsutil, Contig on all NTFS drives)?" -Default "Y") {
    $contigOutputs = @{}
    $dirtyVolumes = @()
    $lowSpaceDrives = @()
    $diskErrors = 0
    $diskRepairs = 0

    foreach ($drive in $ntfsDrives.DriveLetter) {
        $drivePath = "$drive`:"
        Write-Log "Processing disk maintenance for $drivePath..."

        # fsutil dirty query
        $dirtyStatus = fsutil dirty query $drivePath
        if ($dirtyStatus -match "IS dirty") {
            Write-Log "$drivePath is marked dirty. Scheduling CHKDSK..."
            $dirtyVolumes += $drivePath
            chkdsk $drivePath /f
            $diskRepairs++
            Write-Host "`n$drivePath Status: Marked dirty, CHKDSK /f scheduled" -ForegroundColor Yellow
        } else {
            Write-Host "`n$drivePath Status: Not dirty" -ForegroundColor Green
        }

        # Free space check
        $volumeInfo = Get-Volume -DriveLetter $drive
        if ($volumeInfo.SizeRemaining / $volumeInfo.Size -lt 0.1) {
            Write-Log "Low free space on $drivePath (<10%). Recommend cleanup."
            $lowSpaceDrives += $drivePath
            Write-Host "$drivePath Status: Low free space (<10%)" -ForegroundColor Yellow
        } else {
            Write-Host "$drivePath Status: Sufficient free space" -ForegroundColor Green
        }

        # fsutil repair state
        Write-Log "Checking corruption state of $drivePath with fsutil..."
        $repairState = fsutil repair state $drivePath
        $repairState | Out-File -FilePath $logFile -Append
        if ($repairState -match "0x00") {
            Write-Log "$drivePath is clean (0x00). No fsutil/chkdsk repair needed."
            Write-Host "$drivePath Status: Clean (0x00)" -ForegroundColor Green
        } else {
            Write-Log "$drivePath has corruption ($repairState). Initiating online repair..."
            fsutil repair initiate $drivePath
            Write-Log "Online repair initiated. Scheduling chkdsk /f /sdcleanup..."
            chkdsk $drivePath /f /sdcleanup
            Write-Log "chkdsk /f /sdcleanup scheduled. Reboot may be required."
            $diskRepairs++
            Write-Host "$drivePath Status: Corruption detected ($repairState), CHKDSK /f /sdcleanup scheduled" -ForegroundColor Yellow
            $diskErrors++
        }

        # CHKDSK /scan
        $chkdskScanCmd = "chkdsk /scan $drivePath"
        Write-Host "`nRunning CHKDSK Scan on $drivePath" -ForegroundColor Cyan
        if (Confirm-Action -Message "Proceed with CHKDSK Scan on $drivePath?" -Default "Y") {
            Write-Log "Executing: $chkdskScanCmd"
            $output = Invoke-Expression "$chkdskScanCmd 2>&1" | Tee-Object -FilePath $logFile -Append
            if ($output -match "found.*bad|corruption|error") {
                Write-Host "`nCHKDSK Scan Result: Errors found on $drivePath" -ForegroundColor Yellow
                Write-Log "CHKDSK Scan: Errors found on $drivePath"
                $diskErrors++
            } else {
                Write-Host "`nCHKDSK Scan Result: No errors found on $drivePath" -ForegroundColor Green
                Write-Log "CHKDSK Scan: No errors found on $drivePath"
            }
            Write-Log "End of CHKDSK Scan on $drivePath"
        } else {
            Write-Log "Skipped CHKDSK Scan on $drivePath"
            Write-Host "`nCHKDSK Scan Result: Skipped for $drivePath" -ForegroundColor Green
        }

        # Contig on MFT
        if ($contigAvailable) {
            $contigCmd = "contig -v -accepteula $drivePath\`$MFT"
            Write-Host "`nRunning Contig on MFT for $drivePath" -ForegroundColor Cyan
            if (Confirm-Action -Message "Proceed with Contig on MFT for $drivePath?" -Default "Y") {
                Write-Log "Executing: $contigCmd"
                $output = Invoke-Expression "$contigCmd 2>&1" | Tee-Object -FilePath $logFile -Append
                $contigOutputs[$drivePath] = $output
                $fragmentMatch = $output | Select-String "is in (\d+) fragments"
                $fragments = if ($fragmentMatch) { [int]$fragmentMatch.Matches.Groups[1].Value } else { 0 }
                if ($output -match "error|failed|cannot open") {
                    Write-Host "`nContig Result: Errors encountered on $drivePath" -ForegroundColor Yellow
                    Write-Log "Contig: Errors encountered on $drivePath"
                    $diskErrors++
                } else {
                    Write-Host "`nContig Result: MFT on $drivePath in $fragments fragments" -ForegroundColor Green
                    Write-Log "Contig: MFT on $drivePath in $fragments fragments"
                }
                Write-Log "End of Contig on $drivePath"
            } else {
                Write-Log "Skipped Contig on $drivePath"
                Write-Host "`nContig Result: Skipped for $drivePath" -ForegroundColor Green
            }
        } else {
            Write-Log "Contig not available. Skipping MFT defragmentation for $drivePath."
            Write-Host "`nContig Result: Skipped for $drivePath (Contig not available)" -ForegroundColor Yellow
        }
    }

    Write-Host "`nDisk Maintenance Summary:" -ForegroundColor Green
    Write-Host "Dirty Volumes: $($dirtyVolumes -join ', ')"
    Write-Host "Low Space Drives: $($lowSpaceDrives -join ', ')"
    Write-Host "Errors Detected: $diskErrors"
    Write-Host "Repairs/Scheduled Fixes: $diskRepairs"
    if ($dirtyVolumes.Count -gt 0) {
        Write-Host "Reboot required to complete CHKDSK fixes on: $($dirtyVolumes -join ', ')" -ForegroundColor Yellow
    }
    Write-Log "Disk Maintenance Summary: Dirty Volumes=$($dirtyVolumes -join ', '), Low Space Drives=$($lowSpaceDrives -join ', '), Errors=$diskErrors, Repairs=$diskRepairs"
    if ($dirtyVolumes.Count -gt 0) {
        Write-Log "Reboot required to complete CHKDSK fixes on: $($dirtyVolumes -join ', ')"
    }
} else {
    Write-Log "Skipped Disk Maintenance section"
    Write-Host "`nDisk Maintenance Summary: Skipped" -ForegroundColor Green
}

# Shadow Copy Maintenance Section
if (Confirm-Action -Message "Proceed with Shadow Copy Maintenance (check and fix corruption on all NTFS drives)?" -Default "Y") {
    $shadowStates = @{}
    $corruptedShadows = 0
    $shadowsDeleted = 0
    $restorePointCreated = $false

    foreach ($drive in $ntfsDrives.DriveLetter) {
        $drivePath = "$drive`:"
        Write-Log "Processing shadow copy maintenance for $drivePath..."

        $shadowList = vssadmin list shadows /for=$drivePath
        $shadowList | Out-File -FilePath $logFile -Append
        $shadowCopies = $shadowList | Select-String "Shadow Copy ID: {(.+?)}" | ForEach-Object { $_.Matches.Groups[1].Value }
        $shadowVolumes = $shadowList | Select-String "Shadow Copy Volume: (.+?)$" | ForEach-Object { $_.Matches.Groups[1].Value }

        if ($shadowCopies) {
            Write-Log "Found $($shadowCopies.Count) shadow copies for $drivePath."
            Write-Host "`n$drivePath Shadow Copies: Found $($shadowCopies.Count)" -ForegroundColor Green
            $driveShadowStates = @()
            for ($i = 0; $i -lt $shadowCopies.Count; $i++) {
                $shadowId = $shadowCopies[$i]
                $shadowVolume = $shadowVolumes[$i]
                Write-Log "Checking corruption state of shadow copy: $shadowVolume (ID: $shadowId)"
                $shadowRepairState = fsutil repair state $shadowVolume
                $shadowRepairState | Out-File -FilePath $logFile -Append
                $driveShadowStates += $shadowRepairState
                if ($shadowRepairState -match "0x00") {
                    Write-Log "Shadow copy $shadowVolume is clean (0x00)."
                    Write-Host "Shadow Copy $shadowVolume: Clean (0x00)" -ForegroundColor Green
                } else {
                    Write-Log "Shadow copy $shadowVolume is corrupted ($shadowRepairState). Deleting..."
                    vssadmin delete shadows /shadow=$shadowId /quiet
                    Write-Log "Deleted corrupted shadow copy $shadowId for $drivePath."
                    Write-Host "Shadow Copy $shadowVolume: Corrupted ($shadowRepairState), deleted" -ForegroundColor Yellow
                    $corruptedShadows++
                    $shadowsDeleted++
                }
            }
            $shadowStates[$drivePath] = $driveShadowStates
        } else {
            Write-Log "No shadow copies found for $drivePath."
            Write-Host "`n$drivePath Shadow Copies: None found" -ForegroundColor Green
        }
    }

    if ($ntfsDrives.DriveLetter -contains "C" -and ($shadowStates.Values | ForEach-Object { $_ | Select-String "0x00" -NotMatch })) {
        Write-Log "Creating new restore point for C:..."
        try {
            Checkpoint-Computer -Description "Post-ShadowCopyCleanup Restore Point $((Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))" -RestorePointType MODIFY_SETTINGS
            Write-Log "New restore point created successfully for C:."
            Write-Host "`nC: Restore Point: Created successfully" -ForegroundColor Green
            $restorePointCreated = $true
        } catch {
            Write-Log "Error creating restore point for C:: $_"
            Write-Host "`nC: Restore Point: Error - $_" -ForegroundColor Red
        }
    }

    Write-Host "`nShadow Copy Maintenance Summary:" -ForegroundColor Green
    Write-Host "Corrupted Shadow Copies: $corruptedShadows"
    Write-Host "Shadow Copies Deleted: $shadowsDeleted"
    Write-Host "New Restore Point for C: $(if ($restorePointCreated) { 'Created' } else { 'Not created' })"
    Write-Log "Shadow Copy Maintenance Summary: Corrupted Shadows=$corruptedShadows, Shadows Deleted=$shadowsDeleted, Restore Point Created=$($restorePointCreated)"
} else {
    Write-Log "Skipped Shadow Copy Maintenance section"
    Write-Host "`nShadow Copy Maintenance Summary: Skipped" -ForegroundColor Green
}

# Optimization Section (defrag with drive type check)
if (Confirm-Action -Message "Proceed with Drive Optimization (defrag /C /O /V for SSDs, prompt for non-SSDs)?" -Default "Y") {
    $defragErrors = 0
    $defragOptimizations = 0
    Write-Log "Checking drive types for optimization..."
    if ($ssdDrives) {
        Write-Log "Running defrag /C /O /V for SSD drives: $($ssdDrives -join ', ')"
        $defragOutput = defrag /C /O /V 2>&1  # TRIM for SSDs
        $defragOutput | Out-File -FilePath $logFile -Append
        if ($defragOutput -match "optimized|trimmed") {
            Write-Host "`nSSD Optimization Result: TRIM completed for $($ssdDrives -join ', ')" -ForegroundColor Green
            Write-Log "SSD optimization (TRIM) completed."
            $defragOptimizations++
        } elseif ($defragOutput -match "error|failed") {
            Write-Host "`nSSD Optimization Result: Errors encountered" -ForegroundColor Yellow
            Write-Log "SSD optimization: Errors encountered"
            $defragErrors++
        }
    }
    if ($nonSsdDrives) {
        Write-Log "Non-SSD drives detected: $($nonSsdDrives -join ', '). Defragmentation may take significant time."
        if (Confirm-Action -Message "Proceed with defrag /C /O /V for non-SSD drives (may be time-consuming)?" -Default "N") {
            Write-Log "Running defrag /C /O /V for non-SSD drives..."
            $defragOutput = defrag /C /O /V 2>&1
            $defragOutput | Out-File -FilePath $logFile -Append
            if ($defragOutput -match "defragmented") {
                Write-Host "`nNon-SSD Optimization Result: Defragmentation completed for $($nonSsdDrives -join ', ')" -ForegroundColor Green
                Write-Log "Non-SSD defragmentation completed."
                $defragOptimizations++
            } elseif ($defragOutput -match "error|failed") {
                Write-Host "`nNon-SSD Optimization Result: Errors encountered" -ForegroundColor Yellow
                Write-Log "Non-SSD defragmentation: Errors encountered"
                $defragErrors++
            }
        } else {
            Write-Log "Skipped defragmentation for non-SSD drives."
            Write-Host "`nNon-SSD Optimization Result: Skipped for $($nonSsdDrives -join ', ')" -ForegroundColor Green
        }
    }
    if (-not $ssdDrives -and -not $nonSsdDrives) {
        Write-Log "No drives eligible for optimization."
        Write-Host "`nDrive Optimization Result: No eligible drives" -ForegroundColor Green
    }

    Write-Host "`nDrive Optimization Summary:" -ForegroundColor Green
    Write-Host "Errors Detected: $defragErrors"
    Write-Host "Optimizations Performed: $defragOptimizations"
    Write-Log "Drive Optimization Summary: Errors=$defragErrors, Optimizations=$defragOptimizations"
} else {
    Write-Log "Skipped Drive Optimization section"
    Write-Host "`nDrive Optimization Summary: Skipped" -ForegroundColor Green
}

# Temp File Cleanup Section
if (Confirm-Action -Message "Proceed with Temp File Cleanup (system/user temp, Windows Update cache)?" -Default "Y") {
    Write-Log "Starting Temp File Cleanup..."
    $totalBytesFreed = 0
    $cleanupErrors = 0

    # Helper function to calculate folder size
    function Get-FolderSize {
        param($Path)
        try {
            if (Test-Path $Path) {
                $size = (Get-ChildItem $Path -Recurse -File -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum -ErrorAction SilentlyContinue).Sum
                return [math]::Round($size / 1MB, 2)  # Return size in MB
            }
            return 0
        } catch {
            Write-Log "Error calculating size for ${Path}: $_"
            Write-Host "`nFolder Size Calculation Result for ${Path}: Error - $_" -ForegroundColor Red
            return 0
        }
    }

    # System temp: C:\Windows\Temp
    $sysTempPath = "C:\Windows\Temp"
    Write-Log "Cleaning $sysTempPath..."
    $beforeSize = Get-FolderSize -Path $sysTempPath
    try {
        Get-ChildItem $sysTempPath -Recurse -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
        $afterSize = Get-FolderSize -Path $sysTempPath
        $freed = $beforeSize - $afterSize
        $totalBytesFreed += $freed
        Write-Log "Freed $freed MB from $sysTempPath"
        Write-Host "`nSystem Temp Cleanup Result: Freed $freed MB from $sysTempPath" -ForegroundColor Green
    } catch {
        Write-Log "Error cleaning ${sysTempPath}: $_"
        Write-Host "`nSystem Temp Cleanup Result: Error cleaning ${sysTempPath} - $_" -ForegroundColor Red
        $cleanupErrors++
    }

    # User temp: %TEMP%
    $userTempPath = $env:TEMP
    Write-Log "Cleaning $userTempPath..."
    $beforeSize = Get-FolderSize -Path $userTempPath
    try {
        Get-ChildItem $userTempPath -Recurse -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
        $afterSize = Get-FolderSize -Path $userTempPath
        $freed = $beforeSize - $afterSize
        $totalBytesFreed += $freed
        Write-Log "Freed $freed MB from $userTempPath"
        Write-Host "`nUser Temp Cleanup Result: Freed $freed MB from $userTempPath" -ForegroundColor Green
    } catch {
        Write-Log "Error cleaning ${userTempPath}: $_"
        Write-Host "`nUser Temp Cleanup Result: Error cleaning ${userTempPath} - $_" -ForegroundColor Red
        $cleanupErrors++
    }

    # Windows Update cache: C:\Windows\SoftwareDistribution\Download
    $updatePath = "C:\Windows\SoftwareDistribution\Download"
    Write-Log "Cleaning Windows Update cache ($updatePath)..."
    try {
        Stop-Service -Name wuauserv -Force -ErrorAction SilentlyContinue
        $beforeSize = Get-FolderSize -Path $updatePath
        Get-ChildItem $updatePath -Recurse -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
        $afterSize = Get-FolderSize -Path $updatePath
        $freed = $beforeSize - $afterSize
        $totalBytesFreed += $freed
        Write-Log "Freed $freed MB from $updatePath"
        Write-Host "`nWindows Update Cache Cleanup Result: Freed $freed MB from $updatePath" -ForegroundColor Green
        Start-Service -Name wuauserv -ErrorAction SilentlyContinue
    } catch {
        Write-Log "Error cleaning ${updatePath}: $_"
        Write-Host "`nWindows Update Cache Cleanup Result: Error cleaning ${updatePath} - $_" -ForegroundColor Red
        $cleanupErrors++
        Start-Service -Name wuauserv -ErrorAction SilentlyContinue
    }

    Write-Log "Temp File Cleanup completed. Total freed: $totalBytesFreed MB, Errors: $cleanupErrors"
    Write-Host "`nTemp File Cleanup Summary:" -ForegroundColor Green
    Write-Host "Total Space Freed: $totalBytesFreed MB"
    Write-Host "Errors Encountered: $cleanupErrors"
} else {
    Write-Log "Skipped Temp File Cleanup"
    Write-Host "`nTemp File Cleanup Summary: Skipped" -ForegroundColor Green
}

# Hardware and Driver Checks Section
if (Confirm-Action -Message "Proceed with Hardware and Driver Checks (SMART, drivers)?" -Default "Y") {
    $physicalDisks = Get-PhysicalDisk
    $reliability = $physicalDisks | Get-StorageReliabilityCounter
    $smartIssues = 0
    foreach ($disk in $physicalDisks) {
        if ($disk.HealthStatus -ne "Healthy") {
            Write-Log "Unhealthy disk: $($disk.DeviceId) - Status: $($disk.HealthStatus)"
            Write-Host "`nDisk $($disk.DeviceId) Status: Unhealthy - $($disk.HealthStatus)" -ForegroundColor Yellow
            $smartIssues++
        } else {
            Write-Host "`nDisk $($disk.DeviceId) Status: Healthy" -ForegroundColor Green
        }
    }
    foreach ($counter in $reliability) {
        if ($counter.ReadErrorsTotal -gt 0 -or $counter.WriteErrorsTotal -gt 0 -or $counter.Wear -gt 90) {
            Write-Log "SMART issues on disk: ReadErrors=$($counter.ReadErrorsTotal), WriteErrors=$($counter.WriteErrorsTotal), Wear=$($counter.Wear)%"
            Write-Host "Disk SMART Issues: ReadErrors=$($counter.ReadErrorsTotal), WriteErrors=$($counter.WriteErrorsTotal), Wear=$($counter.Wear)%" -ForegroundColor Yellow
            $smartIssues++
        }
    }

    $problemDrivers = Get-WmiObject Win32_PnPSignedDriver | Where-Object { $_.Status -ne "OK" -or -not $_.IsSigned }
    $driverIssues = if ($problemDrivers) { $problemDrivers.Count } else { 0 }
    if ($problemDrivers) {
        Write-Log "Problem drivers found: $($problemDrivers.Count). Running pnputil /scan-devices..."
        Write-Host "`nDriver Check Result: $driverIssues problem drivers found, running pnputil /scan-devices" -ForegroundColor Yellow
        pnputil /scan-devices
    } else {
        Write-Host "`nDriver Check Result: No problem drivers found" -ForegroundColor Green
        Write-Log "No problem drivers found."
    }

    Write-Host "`nHardware and Driver Checks Summary:" -ForegroundColor Green
    Write-Host "SMART Issues: $smartIssues"
    Write-Host "Problem Drivers: $driverIssues"
    if ($smartIssues -gt 0) {
        Write-Host "Recommendation: Run full hardware diagnostics (e.g., CrystalDiskInfo)" -ForegroundColor Yellow
    }
    Write-Log "Hardware and Driver Checks Summary: SMART Issues=$smartIssues, Problem Drivers=$driverIssues"
} else {
    Write-Log "Skipped Hardware and Driver Checks"
    Write-Host "`nHardware and Driver Checks Summary: Skipped" -ForegroundColor Green
}

# Memory and Update Checks Section
if (Confirm-Action -Message "Proceed with Memory and Update Checks?" -Default "Y") {
    $pendingReboot = Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired"
    $failedUpdates = Get-HotFix | Where-Object { $_.Status -ne "Succeeded" }
    $failedUpdateCount = if ($failedUpdates) { $failedUpdates.Count } else { 0 }
    $memoryDiagnosticScheduled = $false

    if ($pendingReboot) {
        Write-Log "Pending reboot detected. Recommend reboot after script."
        Write-Host "`nUpdate Check Result: Pending reboot detected" -ForegroundColor Yellow
    } else {
        Write-Host "`nUpdate Check Result: No pending reboot" -ForegroundColor Green
    }

    if ($failedUpdates) {
        Write-Log "Failed updates found: $($failedUpdates.Count). Running wuauclt /detectnow..."
        Write-Host "Update Check Result: $failedUpdateCount failed updates found, running wuauclt /detectnow" -ForegroundColor Yellow
        wuauclt /detectnow
    } else {
        Write-Host "Update Check Result: No failed updates found" -ForegroundColor Green
        Write-Log "No failed updates found."
    }

    if (Confirm-Action -Message "Schedule Windows Memory Diagnostic on next reboot?" -Default "N") {
        mdsched.exe /scheduleboot
        Write-Log "Memory Diagnostic scheduled on next reboot."
        Write-Host "`nMemory Diagnostic Result: Scheduled for next reboot" -ForegroundColor Green
        $memoryDiagnosticScheduled = $true
    } else {
        Write-Host "`nMemory Diagnostic Result: Not scheduled" -ForegroundColor Green
    }

    Write-Host "`nMemory and Update Checks Summary:" -ForegroundColor Green
    Write-Host "Pending Reboot: $(if ($pendingReboot) { 'Yes' } else { 'No' })"
    Write-Host "Failed Updates: $failedUpdateCount"
    Write-Host "Memory Diagnostic: $(if ($memoryDiagnosticScheduled) { 'Scheduled' } else { 'Not scheduled' })"
    Write-Log "Memory and Update Checks Summary: Pending Reboot=$($pendingReboot), Failed Updates=$failedUpdateCount, Memory Diagnostic=$($memoryDiagnosticScheduled)"
} else {
    Write-Log "Skipped Memory and Update Checks"
    Write-Host "`nMemory and Update Checks Summary: Skipped" -ForegroundColor Green
}

# Malware Scan Section
if (Confirm-Action -Message "Proceed with Quick Malware Scan (Windows Defender)?" -Default "Y") {
    Write-Log "Running Quick Malware Scan..."
    Start-MpScan -ScanType QuickScan
    $defenderEvents = Get-WinEvent -FilterHashtable @{LogName='Microsoft-Windows-Windows Defender/Operational'; ID=@(1000,1001); StartTime=(Get-Date).AddHours(-1)} -ErrorAction SilentlyContinue
    $threats = $defenderEvents | Where-Object { $_.Message -match "threat detected" }
    $threatCount = if ($threats) { $threats.Count } else { 0 }
    if ($threats) {
        Write-Log "Threats detected: $($threats.Count). Recommend full scan."
        Write-Host "`nMalware Scan Result: $threatCount threats detected, recommend full scan" -ForegroundColor Yellow
    } else {
        Write-Log "No threats found in quick scan."
        Write-Host "`nMalware Scan Result: No threats found" -ForegroundColor Green
    }

    Write-Host "`nMalware Scan Summary:" -ForegroundColor Green
    Write-Host "Threats Detected: $threatCount"
    Write-Log "Malware Scan Summary: Threats Detected=$threatCount"
} else {
    Write-Log "Skipped Malware Scan"
    Write-Host "`nMalware Scan Summary: Skipped" -ForegroundColor Green
}

# Verify VSS service
Write-Log "Checking Volume Shadow Copy Service (VSS) status..."
$vssStatus = Get-Service -Name VSS
if ($vssStatus.Status -eq "Running") {
    Write-Log "VSS service is running."
    Write-Host "`nVSS Service Status: Running" -ForegroundColor Green
} else {
    Write-Log "VSS service is not running. Starting VSS..."
    Start-Service -Name VSS
    Write-Log "VSS service started."
    Write-Host "`nVSS Service Status: Started" -ForegroundColor Green
}

# Log and Event Log Analysis Section
if (Confirm-Action -Message "Proceed with expanded log analysis?" -Default "Y") {
    $dismLogPath = "$env:windir\Logs\DISM\dism.log"
    $cbsLogPath = "$env:windir\Logs\CBS\cbs.log"
    
    $dismErrors = 0
    $dismRepairs = 0
    $cbsErrors = 0
    $cbsRepairs = 0
    $chkdskErrors = 0
    $chkdskRepairs = 0
    $contigErrorsPerDrive = @{}
    $contigFragmentsPerDrive = @{}
    $fsutilCorruptedDrives = 0
    $shadowCorrupted = 0
    $defragErrors = 0
    $defragOptimizations = 0
    $diskErrors = 0
    $driverErrors = 0
    $hardwareErrors = 0
    $vssErrors = 0
    $cleanupErrors = 0
    $totalBytesFreed = 0
    
    $errorPattern = "error|failed|failure|corrupt"
    $repairPattern = "repaired|restored|fixed|successfully repaired"
    $chkdskErrorPattern = "found \d+ bad|corruption|error"
    $chkdskRepairPattern = "repaired|fixed|corrected|cleaned"
    $contigErrorPattern = "error|failed|cannot open"
    $contigFragmentPattern = "is in (\d+) fragments"
    $fsutilCorruptionPattern = "0x[1-9A-F]"
    $shadowCorruptionPattern = "0x[1-9A-F]"
    $defragErrorPattern = "error|failed"
    $defragOptPattern = "optimized|trimmed|defragmented"
    $cleanupErrorPattern = "Error cleaning.*Temp|SoftwareDistribution"
    
    if (Test-Path $dismLogPath) {
        $dismErrors = (Select-String -Path $dismLogPath -Pattern $errorPattern -CaseSensitive:$false | Measure-Object).Count
        $dismRepairs = (Select-String -Path $dismLogPath -Pattern $repairPattern -CaseSensitive:$false | Measure-Object).Count
    } else {
        Write-Log "DISM.log not found at $dismLogPath"
    }
    
    if (Test-Path $cbsLogPath) {
        $cbsErrors = (Select-String -Path $cbsLogPath -Pattern $errorPattern -CaseSensitive:$false | Measure-Object).Count
        $cbsRepairs = (Select-String -Path $cbsLogPath -Pattern $repairPattern -CaseSensitive:$false | Measure-Object).Count
    } else {
        Write-Log "CBS.log not found at $cbsLogPath"
    }
    
    $eventIds = @(7,11,50,55,98,137,140,153,219,41,7023,2004,1001,12289,12290)
    $systemEvents = Get-WinEvent -FilterHashtable @{LogName='System'; ID=$eventIds; StartTime=(Get-Date).AddHours(-48)} -ErrorAction SilentlyContinue
    $appEvents = Get-WinEvent -FilterHashtable @{LogName='Application'; ID=$eventIds; StartTime=(Get-Date).AddHours(-48)} -ErrorAction SilentlyContinue
    $allEvents = $systemEvents + $appEvents

    $diskErrors = $allEvents | Where-Object { $_.Id -in @(7,11,50,55,98,137,140,153) } | Measure-Object | Select -Expand Count
    $driverErrors = $allEvents | Where-Object { $_.Id -in @(219,7023) } | Measure-Object | Select -Expand Count
    $hardwareErrors = $allEvents | Where-Object { $_.Id -in @(41,2004,1001) } | Measure-Object | Select -Expand Count
    $vssErrors = $allEvents | Where-Object { $_.Id -in @(12289,12290) } | Measure-Object | Select -Expand Count
    
    foreach ($drivePath in $contigOutputs.Keys) {
        $output = $contigOutputs[$drivePath]
        $contigErrorsPerDrive[$drivePath] = ($output | Select-String -Pattern $contigErrorPattern -CaseSensitive:$false | Measure-Object).Count
        $fragmentMatch = $output | Select-String -Pattern $contigFragmentPattern -CaseSensitive:$false
        if ($fragmentMatch) {
            $contigFragmentsPerDrive[$drivePath] = [int]($fragmentMatch.Matches.Groups[1].Value)
        } else {
            $contigFragmentsPerDrive[$drivePath] = 0
        }
    }
    
    $fsutilCorruptedDrives = (Select-String -Path $logFile -Pattern $fsutilCorruptionPattern | Measure-Object).Count
    foreach ($states in $shadowStates.Values) {
        $shadowCorrupted += ($states | Select-String -Pattern $shadowCorruptionPattern | Measure-Object).Count
    }
    $defragErrors = (Select-String -Path $logFile -Pattern $defragErrorPattern -CaseSensitive:$false | Measure-Object).Count
    $defragOptimizations = (Select-String -Path $logFile -Pattern $defragOptPattern -CaseSensitive:$false | Measure-Object).Count
    $cleanupErrors = (Select-String -Path $logFile -Pattern $cleanupErrorPattern -CaseSensitive:$false | Measure-Object).Count
    $totalBytesFreed = ($logFile | Select-String "Freed (\d+\.?\d*) MB" | ForEach-Object { [double]$_.Matches.Groups[1].Value } | Measure-Object -Sum).Sum
    
    Write-Host "`nLog Analysis Summary:" -ForegroundColor Green
    Write-Host "DISM.log Errors/Failures: $dismErrors"
    Write-Host "DISM.log Repairs: $dismRepairs"
    Write-Host "CBS.log Errors/Failures: $cbsErrors"
    Write-Host "CBS.log Repairs: $cbsRepairs"
    Write-Host "CHKDSK Event Log Errors: $chkdskErrors"
    Write-Host "CHKDSK Event Log Repairs: $chkdskRepairs"
    foreach ($drivePath in $contigErrorsPerDrive.Keys) {
        $driveType = ($ntfsDrives | Where-Object { $_.DriveLetter -eq $drivePath[0] }).MediaType
        Write-Host "Contig Errors on $drivePath ($driveType): $($contigErrorsPerDrive[$drivePath])"
        Write-Host "Contig MFT Fragments on $drivePath ($driveType): $($contigFragmentsPerDrive[$drivePath])"
    }
    Write-Host "fsutil Corrupted Drives: $fsutilCorruptedDrives"
    Write-Host "Shadow Copy Corrupted Instances: $shadowCorrupted"
    Write-Host "Defrag Errors: $defragErrors"
    Write-Host "Defrag Optimizations: $defragOptimizations"
    Write-Host "Temp File Cleanup Errors: $cleanupErrors"
    Write-Host "Temp File Cleanup Freed (MB): $totalBytesFreed"
    Write-Host "Disk/NTFS Errors (IDs 7,11,50,55,98,137,140,153): $diskErrors"
    Write-Host "Driver Errors (IDs 219,7023): $driverErrors"
    Write-Host "Hardware/Memory Errors (IDs 41,2004,1001): $hardwareErrors"
    Write-Host "VSS Errors (IDs 12289,12290): $vssErrors"
    Write-Host "Total Errors/Failures: $totalErrors"
    Write-Host "Total Repairs/Optimizations: $totalRepairs"

    $recommendations = @()
    if ($diskErrors -gt 0) { $recommendations += "Run full CHKDSK /f /r on affected drives (caution on SSDs)." }
    if ($smartIssues -gt 0) { $recommendations += "Check hardware with manufacturer tools (e.g., CrystalDiskInfo)." }
    if ($driverErrors -gt 0) { $recommendations += "Update or rollback drivers via Device Manager." }
    if ($hardwareErrors -gt 0) { $recommendations += "Run memory/hardware diagnostics." }
    if ($vssErrors -gt 0) { $recommendations += "Restart VSS service or clear shadow storage." }
    if ($lowSpaceDrives.Count -gt 0) { $recommendations += "Free up space on $($lowSpaceDrives -join ', ')." }
    if ($threats) { $recommendations += "Run full Defender scan." }
    if ($totalBytesFreed -gt 1000) { $recommendations += "Significant temp files cleared ($totalBytesFreed MB). Consider scheduling regular cleanups." }
    if ($cleanupErrors -gt 0) { $recommendations += "Temp file cleanup encountered errors. Check log for details." }
    if ($recommendations) {
        Write-Host "Recommendations:" -ForegroundColor Yellow
        $recommendations | ForEach-Object { Write-Host "- $_" }
    }

    # Append to log
    "----- Log Analysis Summary at $(Get-Date) -----" | Out-File -FilePath $logFile -Append
    "DISM.log Errors/Failures: $dismErrors" | Out-File -FilePath $logFile -Append
    "DISM.log Repairs: $dismRepairs" | Out-File -FilePath $logFile -Append
    "CBS.log Errors/Failures: $cbsErrors" | Out-File -FilePath $logFile -Append
    "CBS.log Repairs: $cbsRepairs" | Out-File -FilePath $logFile -Append
    "CHKDSK Event Log Errors: $chkdskErrors" | Out-File -FilePath $logFile -Append
    "CHKDSK Event Log Repairs: $chkdskRepairs" | Out-File -FilePath $logFile -Append
    foreach ($drivePath in $contigErrorsPerDrive.Keys) {
        $driveType = ($ntfsDrives | Where-Object { $_.DriveLetter -eq $drivePath[0] }).MediaType
        "Contig Errors on $drivePath ($driveType): $($contigErrorsPerDrive[$drivePath])" | Out-File -FilePath $logFile -Append
        "Contig MFT Fragments on $drivePath ($driveType): $($contigFragmentsPerDrive[$drivePath])" | Out-File -FilePath $logFile -Append
    }
    "fsutil Corrupted Drives: $fsutilCorruptedDrives" | Out-File -FilePath $logFile -Append
    "Shadow Copy Corrupted Instances: $shadowCorrupted" | Out-File -FilePath $logFile -Append
    "Defrag Errors: $defragErrors" | Out-File -FilePath $logFile -Append
    "Defrag Optimizations: $defragOptimizations" | Out-File -FilePath $logFile -Append
    "Temp File Cleanup Errors: $cleanupErrors" | Out-File -FilePath $logFile -Append
    "Temp File Cleanup Freed (MB): $totalBytesFreed" | Out-File -FilePath $logFile -Append
    "Disk/NTFS Errors (IDs 7,11,50,55,98,137,140,153): $diskErrors" | Out-File -FilePath $logFile -Append
    "Driver Errors (IDs 219,7023): $driverErrors" | Out-File -FilePath $logFile -Append
    "Hardware/Memory Errors (IDs 41,2004,1001): $hardwareErrors" | Out-File -FilePath $logFile -Append
    "VSS Errors (IDs 12289,12290): $vssErrors" | Out-File -FilePath $logFile -Append
    "Total Errors/Failures: $totalErrors" | Out-File -FilePath $logFile -Append
    "Total Repairs/Optimizations: $totalRepairs" | Out-File -FilePath $logFile -Append
    if ($recommendations) {
        "Recommendations:" | Out-File -FilePath $logFile -Append
        $recommendations | ForEach-Object { "- $_" | Out-File -FilePath $logFile -Append }
    }
    "----- End of Log Analysis -----" | Out-File -FilePath $logFile -Append
} else {
    Write-Log "Skipped Log Analysis"
    Write-Host "`nLog Analysis Summary: Skipped" -ForegroundColor Green
}

Write-Host "`nAll operations completed. Log file: $logFile" -ForegroundColor Cyan
pause